# Generated by Django 4.1.4 on 2022-12-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('thumb', models.ImageField(upload_to='')),
                ('large', models.ImageField(upload_to='')),
                ('medium', models.ImageField(upload_to='')),
                ('greyscale', models.ImageField(upload_to='')),
            ],
        ),
    ]
